backend:
  name: git-gateway #git-gateway/test-repo
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: public/img
public_folder: img
collections:
  - name: "posts"
    label: "Blog-Beiträge"
    label_singular: "Blog-Beitrag"
    folder: "posts/"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
